### ISSUE TITLE
Using net-snmp gem: Could not open library 'libnetsnmp'

### ISSUE THREAD

**Issue by lebogan** [mixtli/net-snmp#7]
My environment:
# require 'net-snmp'

Gems:
net-snmp (0.2.5)
ffi (1.9.3)
ffi-inliner (0.2.4)
nice-ffi (0.4)

Ruby version:
ruby 2.1.1p76 (2014-02-24 revision 45161) [x86_64-linux]
ruby 1.9.3p547 (2014-05-14 revision 45962) [x86_64-linux]

Libs:
/usr/lib64/libnetsnmp.so.30.0.2
/usr/lib64/libnetsnmp.so.30

**Comment by zealot2007** [comment]
you need to create link using ln -s /usr/lib64/libnetsnmp.so.30 /usr/lib/libnetsnmp.so

**Comment by lebogan** [comment]
Thanks, zealot2007.
